# Generated by Django 3.1 on 2023-12-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='message',
        ),
    ]
