# Generated by Django 3.1 on 2023-12-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20231218_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
