# Generated by Django 3.1 on 2023-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
