# Generated by Django 3.1 on 2023-12-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
