# Generated by Django 3.1 on 2023-12-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerDetails',
        ),
    ]
